// Code generated by protoc-gen-tstypes. DO NOT EDIT.

export enum Status {
    PLACED = "PLACED",
    APPROVED = "APPROVED",
    DELIVERED = "DELIVERED",
}
export interface IDeleteOrderRequest {
    orderId?: number;
}

export interface IGetOrderByIdRequest {
    orderId?: number;
}

export enum GetOrdersRequest_GetOrdersRequestStatus {
    GET_ORDERS_REQUEST_STATUS_PLACED = "GET_ORDERS_REQUEST_STATUS_PLACED",
    GET_ORDERS_REQUEST_STATUS_APPROVED = "GET_ORDERS_REQUEST_STATUS_APPROVED",
    GET_ORDERS_REQUEST_STATUS_DELIVERED = "GET_ORDERS_REQUEST_STATUS_DELIVERED",
}
export interface IGetOrdersRequest {
    limit?: number;
    status?: GetOrdersRequest_GetOrdersRequestStatus;
}

export interface IOrder {
    complete?: boolean;
    id?: number;
    petId?: number;
    quantity?: number;
    shipDate?: string;
    status?: Status;
}

export interface IOrders {
    orders?: IOrder[];
}

export interface IPlaceOrderRequest {
    body?: IOrder;
}

export interface ISwaggerPetstoreServiceService {
    DeleteOrder: (r: IDeleteOrderRequest) => void;
    GetOrderById: (r: IGetOrderByIdRequest) => IOrder;
    GetOrders: (r: IGetOrdersRequest) => IOrders;
    PlaceOrder: (r: IPlaceOrderRequest) => IOrder;
}
